
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.95.1/js/materialize.min.js"></script> -->
<?php
    $helper = $this->helper('Voice\Notification\Helper\Data');
    $customers = $helper->getCustomerLogin();
    $notification = $helper->getcollections();
            // echo "<pre>";
            // print_r($notification->getData()[0]);die;
?>
<?php //foreach ($notification as $collection => $collectionValue):?>
    <?php $language = $notification->getData()[0]['language'];
    $text = $notification->getData()[0]['voice_text'];?>
    <script>
        require( [
            'jquery',
            'jquery/ui',
        ], function ($,ui) {
            'use strict';
            $(function(){
                speechSynthesis;
                var language = '<?= $language;?>';
                var customer = '<?= $customers;?>';
                console.log(language);
                $(window).load(function(){
                // if(customer == 1){
                    var text = '<?= $text;?>';
                    var msg = new SpeechSynthesisUtterance();
                    var voices = window.speechSynthesis.getVoices();
                    // console.log(voices[7]);
                    msg.voice = voices[language];
                    console.log(msg.voice);
                    // msg.rate = $('#rate').val() / 10;
                    // msg.pitch = $('#pitch').val();
                    msg.text = text;
                    console.log(msg.text);

                    msg.onend = function(e) {
                        console.log('Finished in ' + event.elapsedTime + ' seconds.');
                    };
                    console.log(msg)
                    speechSynthesis.speak(msg);
                // }
            });
            });
        });
    </script>
<?php// endforeach;?>