<?php
    $GenericCollection = $block->getCollection();
    $data = $GenericCollection->getData();

    $userName = '';
    for($i=0;$i<count($data);$i++){
        $userName = $data[$i]['username'];
        break;
    }
    $genericSliderId  = $this->getData('generic_sliderId');
?>
<?php for($i=0;$i<count($data);$i++){ ?>
    <?php $genericId = $data[$i]['generic_id']; ?>
    <?php if($genericId == $genericSliderId){ ?>
        <?php if($data[$i]['status']) { ?>
            <section id="instagram-carousel">
                <div class="row">
                    <div class="carousel-wrap">
                        <div class="owl-carousel product-slider">
                            <?php
                                $jsonData = $data[$i]['image_urls'];
                                $imageTagName = $data[$i]['image_tag'];
                                $imageLink = $data[$i]['post_link'];
                                $likes = $data[$i]['likes'];
                                $comments = $data[$i]['comments'];
                                $arrayData = json_decode($jsonData, TRUE);
                                $imageTagNameCollection = json_decode($imageTagName, TRUE);
                                $imageLinkCollection = json_decode($imageLink, TRUE);
                                $imageLikes = json_decode($likes, TRUE);
                                $imageComments = json_decode($comments, TRUE);
                    
                                for ($j=0; $j <count($arrayData); $j++)  { 
                            ?>
                            <a href="<?= $imageLinkCollection[$j];?>" target="blank">
                                <img alt="Owl Image" src='<?php echo $arrayData[$j];  ?>' />
                                <div class="instagram-image-details">
                                    <div class="image-name">
                                        <p>
                                            <?php $captions = substr($imageTagNameCollection[$j], 0, 20)."..."; ?>
                                            <?= __($captions); ?>    
                                        </p>
                                    </div>
                                    <div class="image-like-comment-section">
                                        <div class="image-like">
                                            <span><img src="<?php echo $this->getViewFileUrl('Excellence_Instagram::images/like.png'); ?>" class="instagram-like" alt="instagram-logo"><?= __($imageLikes[$j]); ?></span>
                                        </div>
                                        <div class="image-comment">
                                            <span><img src="<?php echo $this->getViewFileUrl('Excellence_Instagram::images/comment.png'); ?>" class="instagram-comment" alt="instagram-logo"><?= __($imageComments[$j]); ?></span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <?php } ?>
                        </div>
                    </div>
                    <hr>
                </div>
            </section>
        <?php } ?>
    <?php } ?>
<?php } ?>

<script type="text/javascript">
require([
    'jquery',
    'image-slider'
    ], function(jQuery){
        jQuery(document).ready(function(){
            jQuery(".owl-carousel.product-slider").owlCarousel({
                loop:true,
                margin:10,
                nav:true,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:5
                    }
                }
            });
        });
        var owl = jQuery('.owl-carousel.product-slider');
        owl.on('mousewheel', '.owl-stage', function (e) {
            if (e.deltaY>0) {
                owl.trigger('next.owl');
            } else {
                owl.trigger('prev.owl');
            }
            e.preventDefault();
        });
        owl.owlCarousel({
            items:5,
            nav: true,
            dots: false,
            navText: ["<div><img src='<?php echo $this->getViewFileUrl('Excellence_Instagram::images/left-nav.png'); ?>'/></div>","<div><img src='<?php echo $this->getViewFileUrl('Excellence_Instagram::images/right-nav.png'); ?>'/></div>"],
            loop:true,
            margin:10,
            autoplay:true,
            autoplayTimeout:1000,
            autoplayHoverPause:true
        });
       
        var that = this;
        setTimeout(function() {
            owl.trigger('play.owl.autoplay',[1000]);
        }, 10000);
    });
</script>

<style>
.product-slider-heading {
    text-align: -webkit-center;
}
.product-slider-heading .main-heading h3 {
    margin-bottom: 10px;
    font-size: 30px;
    font-weight: 200;
    text-transform: capitalize;
    margin-top: unset;
}
.product-slider-heading .sub-heading p {
    font-size: 18px;
}
.owl-item>div>a>.caption, .slider-main-div>div>a>.caption {
    visibility: hidden;
    position: absolute;
    bottom: 0;
    height: 100%;
    font-size: 20px;
    width: 100%;
    background-color: rgba(27, 26, 26, 0.5);
    text-align: center;
    font-weight: 100;
    color: #fff;
}
</style>